# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.20.1
loader_version=0.18.5
# Mod Properties
mod_version=0.0.1-forge2.5.50.2+mc1.20.1
maven_group=cn.sh1rocu
archives_base_name=goety-fabric
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.92.7+1.20.1
jei_version=15.2.0.27
trinkets_version=3.7.1
patchouli_version=81-FABRIC
jade_version=11.13.1+fabric
cca_version=5.2.3
forge_config_api_port_version=8.0.2
fabric_asm_version=v2.3
